import puppeteer from 'puppeteer-core';
const CHROME='C:/Program Files/Google/Chrome/Application/chrome.exe';
const BASE='http://localhost:5175/ttrpg-core';
const OUT='C:/Users/andre/cyberfolk/ttrpg-core/outputs/verify';
const seed={version:2,exportedAt:0,characters:[{id:'c1',name:'Aragorn',deletedAt:null}],groups:[],transactions:[]};
const b=await puppeteer.launch({executablePath:CHROME,headless:'new',args:['--no-sandbox']});
const p=await b.newPage();
await p.setViewport({width:900,height:800,deviceScaleFactor:2});
await p.evaluateOnNewDocument(s=>localStorage.setItem('ttrpg-reputation-state',JSON.stringify(s)),seed);
await p.goto(`${BASE}/personaggio/c1`,{waitUntil:'networkidle0'});
const w=ms=>new Promise(r=>setTimeout(r,ms));
await w(500);
await p.evaluate(()=>[...document.querySelectorAll('.led__item')].find(i=>/Razza/.test(i.textContent)).querySelector('.led__val--edit').click());
await w(400);
await p.screenshot({path:`${OUT}/d1-razza-dropdown.png`});
await p.keyboard.press('Escape'); await w(200);
const btns=await p.$$('.led__item .led__val--edit');
await btns[1].click(); await w(300);
await p.evaluate(()=>document.querySelector('.led__mc .isel__trigger').click());
await w(400);
await p.screenshot({path:`${OUT}/d2-classe-lvl-dropdown.png`});
console.log('done');
await b.close();
